collections:
  authors:
        output: true
defaults:
  - scope:
      path: "/smari"
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "/smari"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/smari"
    values:
      layout: "default"
